# Generated by Django 5.1.1 on 2024-09-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='databaseloader',
            name='metric_9',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
