# Generated by Django 5.1.1 on 2024-09-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_ingress', '0003_alter_databaseloader_metric_0_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databaseloader',
            old_name='internal_unique_event_id',
            new_name='internal_unique_client_id',
        ),
    ]
