version: '3.8'

networks:
  elastic_postgresql_network:
    external:
      name: elastic_postgresql_network

services:
  db:
    container_name: postgresql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: streaming_app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - elastic_postgresql_network

volumes:
  pg_data:

